### ISSUE TITLE
support for lua 5.3

### ISSUE THREAD

**Issue by ncopa** [slact/lua-feedparser#3]
It would be great with lua 5.3 support

... and a release tag.

**Comment by ncopa** [comment]
```
Lua 5.3.0  Copyright (C) 1994-2015 Lua.org, PUC-Rio
> f = require'feedparser'
/usr/share/lua/5.3/feedparser/XMLElement.lua:5: attempt to call a nil value (global 'module')
stack traceback:
        /usr/share/lua/5.3/feedparser/XMLElement.lua:5: in main chunk
        [C]: in function 'require'
        /usr/share/lua/5.3/feedparser.lua:2: in main chunk
        [C]: in function 'require'
        stdin:1: in main chunk
        [C]: in ?
```

**Comment by slact** [comment]
It shall be done.

**Comment by slact** [comment]
It has been done. 

There's a small change for 5.3, as documented in the readme:

  local feedparser=require("feedparser")
  -- note that for Lua < 5.3, the require exports a global "feedparser"
  -- In 5.3 and later, it does not.

  https://github.com/slact/lua-feedparser/tree/0.71

(donations accepted at bitcoin:14PXxhmvmv1w2j2rgq6Pde8gDnHS7rwLf2 if you are so inclined)
